FROM node:22-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Expose the port React dev server runs on
EXPOSE 3000

# Start the application in development mode
CMD ["npm", "start"] 