version: '3.8'

services:
  resume-schema-parser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-schema-parser
    restart: always
    ports:
      - "8022:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    networks:
      - resume-network

  # Uncomment below if you want to add a database service like MongoDB
  # mongodb:
  #   image: mongo:latest
  #   container_name: resume-mongodb
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #   networks:
  #     - resume-network

networks:
  resume-network:
    driver: bridge

# Uncomment if you add MongoDB
# volumes:
#   mongodb_data:
#     driver: local 